--  Generated by Sml_Ada.Machines.Codegen.  Do not edit.
with Hw_Defs; use Hw_Defs;
package Hw_Compiled is
   type Machine is record
      Current : State;
   end record;
   function Make (Initial : State) return Machine;
   function State_Of (M : Machine) return State;
   procedure Process_Event
     (M : in out Machine; Ctx : in out Context; Evt : Event);
end Hw_Compiled;
