--  Generated by Sml_Ada.Machines.Codegen.  Do not edit.
package body Tcp_Compiled is
   function Make (Initial : State) return Machine is
     ((Current => Initial));
   function State_Of (M : Machine) return State is
     (M.Current);
   procedure Process_Event
     (M : in out Machine; Ctx : in out Context; Evt : Event)
   is
      K : constant Event_Kind := Kind_Of (Evt);
   begin
      case M.Current is
         when ESTABLISHED =>
            if K = RELEASE and then Evaluate (ALWAYS, Ctx, Evt) then
               Execute (SEND_FIN, Ctx, Evt);
               M.Current := FIN_WAIT_1;
               return;
            end if;
         when FIN_WAIT_1 =>
            if K = ACK and then Evaluate (IS_VALID, Ctx, Evt) then
               Execute (NOTHING, Ctx, Evt);
               M.Current := FIN_WAIT_2;
               return;
            end if;
         when FIN_WAIT_2 =>
            if K = FIN and then Evaluate (IS_VALID, Ctx, Evt) then
               Execute (SEND_ACK, Ctx, Evt);
               M.Current := TIMED_WAIT;
               return;
            end if;
         when TIMED_WAIT =>
            if K = TIMEOUT and then Evaluate (ALWAYS, Ctx, Evt) then
               Execute (NOTHING, Ctx, Evt);
               M.Current := CLOSED;
               return;
            end if;
         when CLOSED =>
            null;
      end case;
   end Process_Event;
end Tcp_Compiled;
