package body Sml_Ada.Machines.Codegen
  with SPARK_Mode => Off
is

   use Ada.Text_IO;

   procedure Put_Dot
     (File    : File_Type;
      Table   : Transition_Table;
      Initial : State;
      Name    : String := "machine") is
   begin
      Put_Line (File, "digraph " & Name & " {");
      Put_Line (File, "   rankdir = LR;");
      Put_Line (File, "   node [shape = box, style = rounded];");
      Put_Line (File, "   __start [shape = point];");
      Put_Line (File, "   __start -> " & Initial'Image & ";");
      for T of Table loop
         Put_Line
           (File,
            "   "
            & T.From'Image
            & " -> "
            & T.To'Image
            & " [label="""
            & T.On'Image
            & " ["
            & T.Guard'Image
            & "] / "
            & T.Action'Image
            & """];");
      end loop;
      Put_Line (File, "}");
   end Put_Dot;

   procedure Put_Compiled_Spec
     (File : File_Type; Defs_Unit : String; Unit : String) is
   begin
      Put_Line
        (File, "--  Generated by Sml_Ada.Machines.Codegen.  Do not edit.");
      Put_Line (File, "with " & Defs_Unit & "; use " & Defs_Unit & ";");
      Put_Line (File, "package " & Unit & " is");
      Put_Line (File, "   type Machine is record");
      Put_Line (File, "      Current : State;");
      Put_Line (File, "   end record;");
      Put_Line (File, "   function Make (Initial : State) return Machine;");
      Put_Line (File, "   function State_Of (M : Machine) return State;");
      Put_Line (File, "   procedure Process_Event");
      Put_Line
        (File,
         "     (M : in out Machine; Ctx : in out Context; Evt : Event);");
      Put_Line (File, "end " & Unit & ";");
   end Put_Compiled_Spec;

   procedure Put_Compiled_Body
     (File      : File_Type;
      Table     : Transition_Table;
      Defs_Unit : String;
      Unit      : String)
   is
      pragma Unreferenced (Defs_Unit);
   begin
      Put_Line
        (File, "--  Generated by Sml_Ada.Machines.Codegen.  Do not edit.");
      Put_Line (File, "package body " & Unit & " is");
      Put_Line (File, "   function Make (Initial : State) return Machine is");
      Put_Line (File, "     ((Current => Initial));");
      Put_Line (File, "   function State_Of (M : Machine) return State is");
      Put_Line (File, "     (M.Current);");
      Put_Line (File, "   procedure Process_Event");
      Put_Line
        (File, "     (M : in out Machine; Ctx : in out Context; Evt : Event)");
      Put_Line (File, "   is");
      Put_Line (File, "      K : constant Event_Kind := Kind_Of (Evt);");
      Put_Line (File, "   begin");
      Put_Line (File, "      case M.Current is");
      for S in State loop
         Put_Line (File, "         when " & S'Image & " =>");
         declare
            Any : Boolean := False;
         begin
            for T of Table loop
               if T.From = S then
                  Any := True;
                  Put_Line
                    (File,
                     "            if K = "
                     & T.On'Image
                     & " and then Evaluate ("
                     & T.Guard'Image
                     & ", Ctx, Evt) then");
                  Put_Line
                    (File,
                     "               Execute ("
                     & T.Action'Image
                     & ", Ctx, Evt);");
                  Put_Line
                    (File, "               M.Current := " & T.To'Image & ";");
                  Put_Line (File, "               return;");
                  Put_Line (File, "            end if;");
               end if;
            end loop;
            if not Any then
               Put_Line (File, "            null;");
            end if;
         end;
      end loop;
      Put_Line (File, "      end case;");
      Put_Line (File, "   end Process_Event;");
      Put_Line (File, "end " & Unit & ";");
   end Put_Compiled_Body;

end Sml_Ada.Machines.Codegen;
